.pragma library

var translations = {
    "es": {
        "General": "General",
        "Tooltip": "Información emergente",
        "Command:": "Comando:",
        "bash -lc '/path/to/script.sh'": "bash -lc '/ruta/al/script.sh'",
        "Edit": "Editar",
        "Open the configured script in the default text editor": "Abrir el script configurado en el editor de texto predeterminado",
        "Set the command to a file path like /path/to/script.sh or ~/script.sh to enable editing": "Establece el comando como una ruta de archivo como /path/to/script.sh o ~/script.sh para habilitar la edición",
        "Refresh (s):": "Actualizar (s):",
        "Run command for tooltip text": "Ejecutar comando para el texto de la información emergente",
        "Default text:": "Texto predeterminado:",
        "Width mode:": "Modo de ancho:",
        "Fill available panel space": "Ocupar el espacio disponible del panel",
        "Padding:": "Relleno:",
        "Font size:": "Tamaño de fuente:",
        "Override font size": "Anular el tamaño de fuente",
        "Font family:": "Familia tipográfica:",
        "Override font family": "Anular la familia tipográfica",
        "Hack": "Hack",
        "Text color:": "Color del texto:",
        "Override theme text color": "Anular el color de texto del tema",
        "Use fixed-width font": "Usar fuente de ancho fijo",
        "Text align:": "Alineación del texto:",
        "Left": "Izquierda",
        "Center": "Centro",
        "Right": "Derecha",
        "Loading…": "Cargando…",
        "No command set": "No se ha configurado ningún comando",
        "No output": "Sin salida",
        "Command failed": "El comando falló",
        "Scriptoid": "Scriptoid"
    },
    "fr": {
        "General": "Général",
        "Tooltip": "Infobulle",
        "Command:": "Commande :",
        "bash -lc '/path/to/script.sh'": "bash -lc '/chemin/vers/script.sh'",
        "Edit": "Éditer",
        "Open the configured script in the default text editor": "Ouvrir le script configuré dans l'éditeur de texte par défaut",
        "Set the command to a file path like /path/to/script.sh or ~/script.sh to enable editing": "Définissez la commande sur un chemin de fichier comme /path/to/script.sh ou ~/script.sh pour activer l'édition",
        "Refresh (s):": "Actualisation (s) :",
        "Run command for tooltip text": "Exécuter une commande pour le texte de l’infobulle",
        "Default text:": "Texte par défaut :",
        "Width mode:": "Mode de largeur :",
        "Fill available panel space": "Occuper l'espace disponible du panneau",
        "Padding:": "Marge intérieure :",
        "Font size:": "Taille de police :",
        "Override font size": "Remplacer la taille de police",
        "Font family:": "Famille de police :",
        "Override font family": "Remplacer la famille de police",
        "Hack": "Hack",
        "Text color:": "Couleur du texte :",
        "Override theme text color": "Remplacer la couleur du texte du thème",
        "Use fixed-width font": "Utiliser une police à chasse fixe",
        "Text align:": "Alignement du texte :",
        "Left": "Gauche",
        "Center": "Centre",
        "Right": "Droite",
        "Loading…": "Chargement…",
        "No command set": "Aucune commande définie",
        "No output": "Aucune sortie",
        "Command failed": "La commande a échoué",
        "Scriptoid": "Scriptoid"
    },
    "hi": {
        "General": "सामान्य",
        "Tooltip": "टूलटिप",
        "Command:": "कमांड:",
        "bash -lc '/path/to/script.sh'": "bash -lc '/path/to/script.sh'",
        "Edit": "संपादित करें",
        "Open the configured script in the default text editor": "कॉन्फ़िगर की गई स्क्रिप्ट को डिफ़ॉल्ट टेक्स्ट एडिटर में खोलें",
        "Set the command to a file path like /path/to/script.sh or ~/script.sh to enable editing": "संपादन सक्षम करने के लिए कमांड को /path/to/script.sh या ~/script.sh जैसे फ़ाइल पथ पर सेट करें",
        "Refresh (s):": "रीफ्रेश (से):",
        "Run command for tooltip text": "टूलटिप पाठ के लिए कमांड चलाएँ",
        "Default text:": "डिफ़ॉल्ट पाठ:",
        "Width mode:": "चौड़ाई मोड:",
        "Fill available panel space": "उपलब्ध पैनल स्थान भरें",
        "Padding:": "पैडिंग:",
        "Font size:": "फ़ॉन्ट आकार:",
        "Override font size": "फ़ॉन्ट आकार बदलें",
        "Font family:": "फ़ॉन्ट परिवार:",
        "Override font family": "फ़ॉन्ट परिवार बदलें",
        "Hack": "Hack",
        "Text color:": "पाठ रंग:",
        "Override theme text color": "थीम का पाठ रंग बदलें",
        "Use fixed-width font": "नियत-चौड़ाई फ़ॉन्ट उपयोग करें",
        "Text align:": "पाठ संरेखण:",
        "Left": "बाएँ",
        "Center": "मध्य",
        "Right": "दाएँ",
        "Loading…": "लोड हो रहा है…",
        "No command set": "कोई कमांड सेट नहीं है",
        "No output": "कोई आउटपुट नहीं",
        "Command failed": "कमांड विफल हुई",
        "Scriptoid": "स्क्रिप्टॉइड"
    },
    "pt": {
        "General": "Geral",
        "Tooltip": "Dica",
        "Command:": "Comando:",
        "bash -lc '/path/to/script.sh'": "bash -lc '/caminho/para/script.sh'",
        "Edit": "Editar",
        "Open the configured script in the default text editor": "Abrir o script configurado no editor de texto predefinido",
        "Set the command to a file path like /path/to/script.sh or ~/script.sh to enable editing": "Defina o comando para um caminho de ficheiro como /path/to/script.sh ou ~/script.sh para ativar a edição",
        "Refresh (s):": "Atualizar (s):",
        "Run command for tooltip text": "Executar comando para o texto da dica",
        "Default text:": "Texto predefinido:",
        "Width mode:": "Modo de largura:",
        "Fill available panel space": "Preencher o espaço disponível no painel",
        "Padding:": "Espaçamento:",
        "Font size:": "Tamanho da fonte:",
        "Override font size": "Substituir o tamanho da fonte",
        "Font family:": "Família da fonte:",
        "Override font family": "Substituir a família da fonte",
        "Hack": "Hack",
        "Text color:": "Cor do texto:",
        "Override theme text color": "Substituir a cor de texto do tema",
        "Use fixed-width font": "Usar fonte de largura fixa",
        "Text align:": "Alinhamento do texto:",
        "Left": "Esquerda",
        "Center": "Centro",
        "Right": "Direita",
        "Loading…": "A carregar…",
        "No command set": "Nenhum comando definido",
        "No output": "Sem saída",
        "Command failed": "O comando falhou",
        "Scriptoid": "Scriptoid"
    },
    "uk": {
        "General": "Загальне",
        "Tooltip": "Підказка",
        "Command:": "Команда:",
        "bash -lc '/path/to/script.sh'": "bash -lc '/шлях/до/script.sh'",
        "Edit": "Редагувати",
        "Open the configured script in the default text editor": "Відкрити налаштований скрипт у типовому текстовому редакторі",
        "Set the command to a file path like /path/to/script.sh or ~/script.sh to enable editing": "Укажіть у команді шлях до файла, наприклад /path/to/script.sh або ~/script.sh, щоб увімкнути редагування",
        "Refresh (s):": "Оновлення (с):",
        "Run command for tooltip text": "Запускати команду для тексту підказки",
        "Default text:": "Типовий текст:",
        "Width mode:": "Режим ширини:",
        "Fill available panel space": "Заповнити доступний простір панелі",
        "Padding:": "Відступ:",
        "Font size:": "Розмір шрифту:",
        "Override font size": "Перевизначити розмір шрифту",
        "Font family:": "Сімейство шрифту:",
        "Override font family": "Перевизначити сімейство шрифту",
        "Hack": "Hack",
        "Text color:": "Колір тексту:",
        "Override theme text color": "Перевизначити колір тексту теми",
        "Use fixed-width font": "Використовувати моноширинний шрифт",
        "Text align:": "Вирівнювання тексту:",
        "Left": "Ліворуч",
        "Center": "По центру",
        "Right": "Праворуч",
        "Loading…": "Завантаження…",
        "No command set": "Команду не задано",
        "No output": "Немає виводу",
        "Command failed": "Помилка виконання команди",
        "Scriptoid": "Скриптоїд"
    },
    "zh_CN": {
        "General": "常规",
        "Tooltip": "工具提示",
        "Command:": "命令：",
        "bash -lc '/path/to/script.sh'": "bash -lc '/path/to/script.sh'",
        "Edit": "编辑",
        "Open the configured script in the default text editor": "在默认文本编辑器中打开已配置的脚本",
        "Set the command to a file path like /path/to/script.sh or ~/script.sh to enable editing": "将命令设置为类似 /path/to/script.sh 或 ~/script.sh 的文件路径以启用编辑",
        "Refresh (s):": "刷新（秒）：",
        "Run command for tooltip text": "为工具提示文本运行命令",
        "Default text:": "默认文本：",
        "Width mode:": "宽度模式：",
        "Fill available panel space": "填充可用面板空间",
        "Padding:": "内边距：",
        "Font size:": "字体大小：",
        "Override font size": "覆盖字体大小",
        "Font family:": "字体族：",
        "Override font family": "覆盖字体族",
        "Hack": "Hack",
        "Text color:": "文本颜色：",
        "Override theme text color": "覆盖主题文本颜色",
        "Use fixed-width font": "使用等宽字体",
        "Text align:": "文本对齐：",
        "Left": "左对齐",
        "Center": "居中",
        "Right": "右对齐",
        "Loading…": "正在加载…",
        "No command set": "未设置命令",
        "No output": "无输出",
        "Command failed": "命令执行失败",
        "Scriptoid": "脚本器"
    }
};

function normalizeLocaleName(localeName) {
    var normalized = String(localeName || "en_US").replace("-", "_").toLowerCase();
    if (normalized.indexOf("zh") === 0)
        return "zh_CN";

    if (normalized.indexOf("pt_br") === 0)
        return "pt";

    return normalized.split("_")[0];
}

function translate(localeName, key, fallback) {
    var language = normalizeLocaleName(localeName);
    var table = translations[language];
    if (table && Object.prototype.hasOwnProperty.call(table, key))
        return table[key];

    return fallback;
}
